//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeOnlineAdmissionPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicDetail
    {
        public int AcademicID { get; set; }
        public int ApplicantID { get; set; }
        public string Qualification { get; set; }
        public string BoardOrUniversity { get; set; }
        public string PassingYear { get; set; }
        public string PercentageOrGPA { get; set; }
        public string UploadMarksheet { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
