//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeOnlineAdmissionPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationForm
    {
        public int FormID { get; set; }
        public int ApplicantID { get; set; }
        public Nullable<int> InchargeID { get; set; }
        public string ProgramAppliedFor { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> MeritRank { get; set; }
        public int ProgramID { get; set; }
        public Nullable<int> MeritListID { get; set; }
    
        public virtual AdmissionIncharge AdmissionIncharge { get; set; }
        public virtual Applicant Applicant { get; set; }
        public virtual MeritList MeritList { get; set; }
        public virtual Program Program { get; set; }
        public double Percentage { get; internal set; }
        public double GPA { get; internal set; }
    }
}
