//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeOnlineAdmissionPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public int ApplicantID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string DocumentType { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Program Program { get; set; }
    }
}
