//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeOnlineAdmissionPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeritList
    {
        internal int ProgramID;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeritList()
        {
            this.ApplicationForms = new HashSet<ApplicationForm>();
        }
    
        public int MeritListID { get; set; }
        public Nullable<int> CreatedByInchargeID { get; set; }
        public string Course { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
    
        public virtual AdmissionIncharge AdmissionIncharge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationForm> ApplicationForms { get; set; }
    }
}
