//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeOnlineAdmissionPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeOnlineAdmissionPortalEntities : DbContext
    {
        public CollegeOnlineAdmissionPortalEntities()
            : base("name=CollegeOnlineAdmissionPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicDetail> AcademicDetails { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<AdmissionIncharge> AdmissionIncharges { get; set; }
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<ApplicationForm> ApplicationForms { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<MeritList> MeritLists { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
